server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=/posts/**, /api/posts/**

        - id: comment-service
          uri: http://localhost:8084
          predicates:
            - Path=/comments/**, /comment-likes/**
        
        - id: follow-service
          uri: http://localhost:8085
          predicates:
            - Path=/follows/**

        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/notifications/**

        - id: media-service
          uri: http://localhost:8087
          predicates:
            - Path=/upload/**, /media/**

        - id: chat-service
          uri: http://localhost:8088
          predicates:
            - Path=/chats/**, /ws/**

        - id: search-service
          uri: http://localhost:8090
          predicates:
            - Path=/search/**
logging:
  level:
    # Log chi tiết nhất về các quyết định định tuyến và filter của Gateway
    org.springframework.cloud.gateway: TRACE
    # Log chi tiết về hoạt động mạng (gửi và nhận request)
    reactor.netty: TRACE